### ISSUE TITLE
Failed to resolve dependency

### ISSUE THREAD

**Issue by oceanlight-cn** [yck1509/ConfuserEx#146]
When Protect, error occurs.
[ERROR] Failed to resolve dependency of 'xx.exe'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) \ConfuserEx\trunk\dnlib\src\DotNet\IAssemblyResolver.cs:line 134
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context)   \ConfuserEx\trunk\Confuser.Core\ConfuserEngine.cs:line 254
[ERROR] Failed to protect packer stub.

**Comment by yck1509** [comment]
Is the log4net dll near the input modules?

**Comment by oceanlight-cn** [comment]
Do you mean include in the input modules? I've already include log4net

**Comment by yck1509** [comment]
Please try the latest commit (5aec5859a9b9923b3b39e84b26c7bc3fe41e2e86) and see if it fixes your problem.

**Comment by HofmeisterAn** [comment]
Had the same bug. I tested 5aec5859a9b9923b3b39e84b26c7bc3fe41e2e86 and it's working.

**Comment by oceanlight-cn** [comment]
yes,it fixes my problem.Thanks.

**Comment by InjectionDev** [comment]
I have a similar issue:

[ERROR] Failed to resolve dependency of 'UnityEditor.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: UnityScript, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in E:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:line 113
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 264
Failed at 17:19, 0:02 elapsed.

**Comment by jameshardennn** [comment]
I also have the same problem when trying to Protect ( [ERROR] Failed to resolve dependency of ' ...... 
I understand that there is a code that needs to be changed but please can you kindly tell me where and how to place the code . I just that know where to find slot and where to edit the source code . 
Please help . 
Thank you
