### ISSUE TITLE
System.FormatException: (Index (ze3ro based)

### ISSUE THREAD

**Issue by cgocgo** [yck1509/ConfuserEx#165]
I have a small solution that obfuscates successfully running the ConfuserEx UI (v0.4.0). My problem is when I try to run it via the command line on the form 
confuserex.cli.exe -n -o=outputdirectory file1 file2 file3 file4
This results in a crash in the Renaming phase. See picture.
![image](https://cloud.githubusercontent.com/assets/10754399/5954426/79b07d6a-a797-11e4-883a-910ded2a7f44.png)

It works when running the commandline with the project-file as an argument. But I can't use the project file since the file paths varies depending on which build server I get for the moment.

I can see a number of reasons.
- Bug?
- I'm giving wrong arguments to the command?

**Comment by ErrCode** [comment]
I'm also encountering this error when using the command line and Declarative Obfuscation (attributes).
```
Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
1>     at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
1>     at System.String.Format(IFormatProvider provider, String format, Object[] args)
1>     at Confuser.CLI.Program.ConsoleLogger.ErrorFormat(String format, Object[] args) in e:\Source\Public\Confuser2\Confuser.CLI\Program.cs:line 168
1>     at Confuser.Core.ProtectionPipeline.<>c__DisplayClass15.<Filter>b__e(IDnlibDef def) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 177
1>     at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
1>     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
1>     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
1>     at Confuser.Core.ProtectionPipeline.Filter(ConfuserContext context, IList`1 targets, ProtectionPhase phase) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 172
1>     at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 141
1>     at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 214
1>     at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 160
```

**Comment by yck1509** [comment]
Please try the latest build at [the CI server](https://ci.appveyor.com/project/yck1509/confuserex) and see whether your issue still presents.

**Comment by DerFetzer** [comment]
I had the same error. The latest build solved the issue for me.
Thank you.

**Comment by jjgh** [comment]
Same here. Last build worked.

**Comment by jjgh** [comment]
I have to stand corrected, I'm still seeing the issue using the latest build: v0.6.0-55-g2b4f482

```
System.FormatException: the value format '2lJWBL5oC(8AU=h__mdnRYZP' google-api-dotnet-client/1.10.0.25331 (gzip)' is not valid.
   in Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   in Google.Apis.Requests.ClientServiceRequest`1.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from the position the exception was generated ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in 2lJWBL5oC(8AU=h__mdnRYZP'._P\&!@R56% {|AUAdO\&ogBhc}.MoveNext()
```
