### ISSUE TITLE
Trying WP8.1 Silverlight App

### ISSUE THREAD

**Issue by scpc0609** [yck1509/ConfuserEx#168]
I selected all the assemblies of my Windows Phone 8.1 (Silverlight) project and applied the below Probe:

C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.1;C:\Program Files (x86)\Microsoft SDKs\Windows Phone\v8.1\Tools\MDILXAPCompile\WinMDs

I am getting the below Exception

[ERROR] Failed to resolve dependency of 'mylib.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in e:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:line 134
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 252
Failed at 4:25 PM, 0:02 elapsed.

It seems that the tool fails to identify Windows.winmd modules.

Any way to make this work or shall I give up because it is not yet supported :) ?

Thanks in advance.

**Comment by 0xd4d** [comment]
Try to apply this dnlib patch to your dnlib: https://github.com/0xd4d/dnlib/commit/ce2e9451c9387b79bda780134dc7581dc578fc6c

**Comment by scpc0609** [comment]
Hi, Thanks for your response. I applied the patch. Then on top I had to add the below code into the AssemblyResolver.cs to remove compilation error in ConfuserEx.

        /// Gets the cached assemblies in this resolver.
        /// </summary>
        /// <returns>The cached assemblies.</returns>
        public IEnumerable<AssemblyDef> GetCachedAssemblies()
        {
            return cachedAssemblies.Values;
        }

I could make the tool work thereafter. Thanks for your help.

**Comment by 0xd4d** [comment]
If you had to add that method you probably just copied the whole file, instead of just applying the patch.

**Comment by scpc0609** [comment]
You are correct! Thanks again.

**Comment by scpc0609** [comment]
But the application on windows phone does not start up.... tried only rename that also could not make it work.

**Comment by yck1509** [comment]
Sorry for the late response! Do you mind sending me your obfuscated file to me at confuser.net@gmail.com for me to have a look?

**Comment by scpc0609** [comment]
Hi, sorry for the late response as I got busy with my release. I am unable to send my live application code, but if you try this with a WP8.1 Silverlight Pivot app template from Visual Studio 2013, you would be able to replicate this issue.

**Comment by yck1509** [comment]
I just took a quick look, and it seems WP8.1 Silverlight uses another binary format for XAML (XBF). It would take some time to support that. Meanwhile, you could try excluding those public classes from renaming (`is-public` pattern may be useful). Other protections should still work.

**Comment by scpc0609** [comment]
Hi, Thanks and I was expecting something going wrong with the BAML. I will have to work considerably to build up the exclusion list and that's not going to be small. I will revert if I can make it working all the way through. Thanks for your co-operation.
