### ISSUE TITLE
Not able to use Packer

### ISSUE THREAD

**Issue by JPVenson** [yck1509/ConfuserEx#218]
Hey,

I cannot protect my files with using the compressor. This will produce this error:

[DEBUG] Encrypting modules...
 [INFO] Protecting packer stub...
[DEBUG] Discovering plugins...
 [INFO] Discovered 11 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
[ERROR] An IO error occurred, check if all input/output locations are readable/writable.
Exception: System.IO.IOException: Could not open file C:\Users\User\AppData\Local\Temp\vr41ehel.pls\Mircrosoft.Windows.Eventlogger.exe for reading. Error: 00000002
   at dnlib.IO.MemoryMappedFileStreamCreator.Windows.Mmap(MemoryMappedFileStreamCreator creator, Boolean mapAsImage) in E:\Source\Public\Confuser2\dnlib\src\IO\MemoryMappedFileStreamCreator.cs:line 67
   at dnlib.IO.MemoryMappedFileStreamCreator.CreateWindows(String fileName, Boolean mapAsImage) in E:\Source\Public\Confuser2\dnlib\src\IO\MemoryMappedFileStreamCreator.cs:line 165
   at dnlib.IO.ImageStreamCreator.Create(String fileName, Boolean mapAsImage) in E:\Source\Public\Confuser2\dnlib\src\IO\ImageStreamCreator.cs:line 42
   at dnlib.PE.PEImage..ctor(String fileName, Boolean mapAsImage, Boolean verify) in E:\Source\Public\Confuser2\dnlib\src\PE\PEImage.cs:line 165
   at dnlib.DotNet.MD.MetaDataCreator.Load(String fileName) in E:\Source\Public\Confuser2\dnlib\src\DotNet\MD\MetaDataCreator.cs:line 35
   at dnlib.DotNet.ModuleDefMD.Load(String fileName, ModuleCreationOptions options) in E:\Source\Public\Confuser2\dnlib\src\DotNet\ModuleDefMD.cs:line 185
   at Confuser.Core.Marker.MarkProject(ConfuserProject proj, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\Marker.cs:line 123
   at Confuser.Core.PackerMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\Packer.cs:line 158
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 122
[ERROR] Failed to protect packer stub.
Failed at 19:20, 0:05 elapsed.

when disabling the compressor, the output is not changed in any way.

**Comment by yck1509** [comment]
Hi,
As indicated by the error message, it cannot write intermediate step files to a temporary location. Please try running it as Administrator. To add protections, you could follow the steps in the [Basic Usage](https://github.com/yck1509/ConfuserEx/wiki/Basic-Usage) wiki page.

**Comment by Caydenz** [comment]
It fails even if it is ran as administrator.

**Comment by yck1509** [comment]
Hi,
Did you used the CLI/GUI version? What settings did you used?

**Comment by Caydenz** [comment]
[ERROR] Failed to resolve a type, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: !NDxe@^IefM-Q!<8`uqDQZm/ (Nice, Version=1.2.2.2, Culture=neutral, PublicKeyToken=null)
   at dnlib.DotNet.TypeRef.ResolveThrow(ModuleDef sourceModule) in E:\Source\Public\Confuser2\dnlib\src\DotNet\TypeRef.cs:line 334
   at dnlib.DotNet.Extensions.ResolveTypeDefThrow(ITypeDefOrRef tdr) in E:\Source\Public\Confuser2\dnlib\src\DotNet\ICodedToken.cs:line 491
   at Confuser.Renamer.Analyzers.InterReferenceAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in e:\Source\Public\Confuser2\Confuser.Renamer\Analyzers\InterReferenceAnalyzer.cs:line 27
   at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 104
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 55
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 138
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 208
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 162
[ERROR] Failed to protect packer stub.
Failed at 19:12, 0:00 elapsed.


I'm using the GUI version.

**Comment by ckovsky** [comment]
I have the same problem when trying to user the compressor from the GUI.
<code>
 [INFO] Loading input modules...
[ERROR] An IO error occurred, check if all input/output locations are readable/writable.
Exception: System.IO.IOException: Could not open file D:\Program\C#\Apps\AmysChoice\bin\Release\AmysChoice.exe for reading. Error: 00000003
   vid dnlib.IO.MemoryMappedFileStreamCreator.Windows.Mmap(MemoryMappedFileStreamCreator creator, Boolean mapAsImage) i E:\Source\Public\Confuser2\dnlib\src\IO\MemoryMappedFileStreamCreator.cs:rad 64
   vid dnlib.IO.MemoryMappedFileStreamCreator.CreateWindows(String fileName, Boolean mapAsImage) i E:\Source\Public\Confuser2\dnlib\src\IO\MemoryMappedFileStreamCreator.cs:rad 164
   vid dnlib.IO.ImageStreamCreator.CreateMemoryMappedFileStreamCreator(String fileName, Boolean mapAsImage) i E:\Source\Public\Confuser2\dnlib\src\IO\ImageStreamCreator.cs:rad 49
   vid dnlib.IO.ImageStreamCreator.Create(String fileName, Boolean mapAsImage) i E:\Source\Public\Confuser2\dnlib\src\IO\ImageStreamCreator.cs:rad 41
   vid dnlib.PE.PEImage..ctor(String fileName, Boolean mapAsImage, Boolean verify) i E:\Source\Public\Confuser2\dnlib\src\PE\PEImage.cs:rad 165
   vid dnlib.DotNet.MD.MetaDataCreator.Load(String fileName) i E:\Source\Public\Confuser2\dnlib\src\DotNet\MD\MetaDataCreator.cs:rad 33
   vid Confuser.Core.Marker.MarkProject(ConfuserProject proj, ConfuserContext context) i e:\Source\Public\Confuser2\Confuser.Core\Marker.cs:rad 100
   vid Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) i e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:rad 121
Failed at 20:12, 0:00 elapsed.
</code>

**Comment by JPVenson** [comment]
Hey,

I used the Guid with nothing other functions. Plain Compressor.

**Comment by yck1509** [comment]
Do you mind posting the full output log of ConfuserEx?

**Comment by stormsw** [comment]
The same problem. It was run as administrator, temp folder is empty, here is a log:
`[DEBUG] Renaming...`
`[DEBUG] Executing 'Anti-debug injection' phase...`
`[DEBUG] Executing 'Anti-dump injection' phase...`
`[DEBUG] Executing 'Anti-ILDasm marking' phase...`
`[DEBUG] Executing 'Encoding reference proxies' phase...`
`[DEBUG] Executing 'Constant encryption helpers injection' phase...`
`[DEBUG] Executing 'Resource encryption helpers injection' phase...`
`[DEBUG] Executing 'Constants encoding' phase...`
`[DEBUG] Executing 'Anti-tamper helpers injection' phase...`
`[DEBUG] Executing 'Control flow mangling' phase...`
`[DEBUG] Executing 'Post-renaming' phase...`
`[DEBUG] Executing 'Anti-tamper metadata preparation' phase...`
`[DEBUG] Executing 'Packer info extraction' phase...`
` [INFO] Writing module 'LicenseProvider.dll'...`
`[DEBUG] Encrypting resources...`
`[DEBUG] Executing 'Packer info extraction' phase...`
` [INFO] Writing module 'Licensing.dll'...`
`[DEBUG] Encrypting resources...`
`[DEBUG] Executing 'Packer info extraction' phase...`
` [INFO] Writing module 'koi'...`
`[DEBUG] Encrypting resources...`
` [INFO] Finalizing...`
` [INFO] Packing...`
`[DEBUG] Encrypting modules...`
`[ERROR] An IO error occurred, check if all input/output locations are readable/writable.`
`Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Alexander\AppData\Local\Temp\a1ani0uw.u0b\LicenseProvider\bin\Release\LicenseProvider.dll'.`
`   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)`
`   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)`
`   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)`
`   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)`
`   at Confuser.Core.Packer.ProtectStub(ConfuserContext context, String fileName, Byte[] module, StrongNameKey snKey, Protection prot) in e:\Source\Public\Confuser2\Confuser.Core\Packer.cs:line 35`
`   at Confuser.Protections.Compressor.Pack(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Protections\Compress\Compressor.cs:line 82`
`   at Confuser.Core.ConfuserEngine.Pack(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 401`
`   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 135`
`   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 243`
`   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 162`
`Failed at 13:11, 0:02 elapsed.`
