### ISSUE TITLE
Add support for IL Merge

### ISSUE THREAD

**Issue by JPVenson** [yck1509/ConfuserEx#219]
Could you please add support for the IL Merge tool? Because its not possible to Confuse a Merged Asseambly that will produce an not found ex

**Comment by yck1509** [comment]
Hi,
To use ILMerge, you could merge the files before processing in ConfuserEx. It might not be able to modify the output of ConfuserEx using ILMerge as it try to preserve integrity of the protected output.

**Comment by JPVenson** [comment]
Hey,

Unfortunately this is not possible, if i try to use ConfuserEx with an ILMerged assambly, the program throws a Reference not found ex.

**Comment by yck1509** [comment]
Hi,
If that is the case then it'll be a bug of ConfuserEx. Do you mind posting the error log / stack trace?

**Comment by bsee08** [comment]
This appears to still be an issue. I have an exe and a dll. Without using ILMerge ConfuserEx works great. Trying to use ConfuserEx after merging the dll with the exe doesn't work. Stacktrace below.

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.   
at Confuser.Core.ConfuserEngine.PrintEnvironmentInfo(ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 512   
at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 179
   at Confuser.Core.ConfuserEngine.<>c__DisplayClass3.<Run>b__2() in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 68
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Confuser.CLI.Program.RunProject(ConfuserParameters parameters) in c:\projects\confuserex\Confuser.CLI\Program.cs:line 132
   at Confuser.CLI.Program.Main(String[] args) in c:\projects\confuserex\Confuser.CLI\Program.cs:line 112

**Comment by yck1509** [comment]
Hi,
Please post the full output log of the ConfuserEx. Also, would it be possible for me to obtain a sample project that would reproduce the issue?

**Comment by bsee08** [comment]
Never mind. The issue is something on my end. When I made a simplified sample project it worked exactly as it should. I ran ConfuserEx, then ILMerge and produced a single obfuscated exe.

**Comment by picrap** [comment]
Have you tried Costura (it is available as a NuGet package)? It is a good alternative to ILMerge.
