### ISSUE TITLE
Thanks and a question

### ISSUE THREAD

**Issue by LaraSQP** [yck1509/ConfuserEx#246]
Thank you for taking the time to develop ConfuserEx and for making it available for free.

Obfuscating a Mono for Android project is giving me some problems. Any clues would be appreciated.

 [INFO] ConfuserEx v0.5.0 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.1.7601 Service Pack 1, .NET Framework v4.0.30319.34209, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'Prog1.dll'...
 [INFO] Loading 'Prog2.dll'...
 [INFO] Loading '..\..\obj\Release\android\assets\shrunk\Mono.Android.dll'...
 [INFO] Loading '..\..\obj\Release\android\assets\shrunk\mscorlib.dll'...
 [INFO] Loading '..\..\obj\Release\android\assets\shrunk\System.Core.dll'...
 [INFO] Loading '..\..\obj\Release\android\assets\shrunk\System.dll'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
 [WARN] [Mono.Android.dll] SN Key is not provided for a signed module, the output may not be working.
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
[ERROR] Failed to resolve a type, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: System.Reflection.AssemblyCultureAttribute (mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at dnlib.DotNet.TypeRef.ResolveThrow(ModuleDef sourceModule) in E:\Source\Public\Confuser2\dnlib\src\DotNet\TypeRef.cs:line 334
   at dnlib.DotNet.Extensions.ResolveTypeDefThrow(ITypeDefOrRef tdr) in E:\Source\Public\Confuser2\dnlib\src\DotNet\ICodedToken.cs:line 491
   at Confuser.Renamer.Analyzers.InterReferenceAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in e:\Source\Public\Confuser2\Confuser.Renamer\Analyzers\InterReferenceAnalyzer.cs:line 27
   at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 104
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 55
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 138
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 208
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 162
[ERROR] ---BEGIN DEBUG INFO---
[ERROR] Installed Framework Versions:
[ERROR]     v2.0.50727  2.0.50727.5420
[ERROR]     v3.0  3.0.30729.5420
[ERROR]     v3.5  3.5.30729.5420
[ERROR]     v4
[ERROR]     Client  4.5.51209
[ERROR]     Full  4.5.51209
[ERROR]     v4.0
[ERROR]     Client  4.0.0.0
[ERROR]     v4.5 379893
[ERROR] 
[ERROR] Cached assemblies:
[ERROR]     Prog1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null ( Y:\Solution\Project\bin\Release\Prog1.dll)
[ERROR]         mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR]         System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR]         Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
[ERROR]     Prog2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null ( Y:\Solution\Project\bin\Release\Prog2.dll)
[ERROR]         Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
[ERROR]         mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR]         Prog1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[ERROR]         System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR]     Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065 ( Y:\Solution\Project\obj\Release\android\assets\shrunk\Mono.Android.dll)
[ERROR]         mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR]         System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR]         System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR]     mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e ( Y:\Solution\Project\obj\Release\android\assets\shrunk\mscorlib.dll)
[ERROR]     System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e ( Y:\Solution\Project\obj\Release\android\assets\shrunk\System.Core.dll)
[ERROR]         mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR]         System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR]     System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e ( Y:\Solution\Project\obj\Release\android\assets\shrunk\System.dll)
[ERROR]         mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[ERROR] ---END DEBUG INFO---
Failed at 4:00 PM, 0:00 elapsed.

**Comment by LaraSQP** [comment]
Found the answer here:

https://github.com/yck1509/ConfuserEx/wiki/Working-with-Xamarin.Android

Thanks again.
