### ISSUE TITLE
Decompressor error

### ISSUE THREAD

**Issue by Praetorian11** [yck1509/ConfuserEx#260]
Hello,
If I switch decompressor to on, I get this error. Can you help me please?

Thank you

[ERROR] Failed to resolve dependency of 'App1.exe'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: NVpaMwDnsVOvvmOynzgTKdAZZYt, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in E:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:line 113
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 254
Failed at 11:37, 0:01 elapsed.

**Comment by XenocodeRCE** [comment]
What is NVpaMwDnsVOvvmOynzgTKdAZZYt ? Is it already obfuscated ?

**Comment by Praetorian11** [comment]
Sorry, it is wrong exception. The correct one is bellow.
Steps to reproduce:

1. Rebuild project
2. Obfuscating w/o compressor - it works
3. Rebuild project
4. Obfuscating with the same parameters - exception invoked

[DEBUG] Encrypting modules...
[ERROR] Unknown error occurred.
Exception: System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Confuser.Protections.Compressor.PackModules(ConfuserContext context, CompressorContext compCtx, ModuleDef stubModule, ICompressionService comp, RandomGenerator random) in e:\Source\Public\Confuser2\Confuser.Protections\Compress\Compressor.cs:line 109
   at Confuser.Protections.Compressor.InjectStub(ConfuserContext context, CompressorContext compCtx, ProtectionParameters parameters, ModuleDef stubModule) in e:\Source\Public\Confuser2\Confuser.Protections\Compress\Compressor.cs:line 262
   at Confuser.Protections.Compressor.Pack(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Protections\Compress\Compressor.cs:line 74
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 135
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 243
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 162
Failed at 17:46, 0:25 elapsed.

**Comment by yck1509** [comment]
Hi,
Are you protecting multiple assemblies with the same name? What settings did you used?

**Comment by yck1509** [comment]
Please try the latest build and see if it solves your problem.
