### ISSUE TITLE
InvalidCastException when obfuscating dll

### ISSUE THREAD

**Issue by arpitpanwar** [yck1509/ConfuserEx#293]
I get an Invalid cast exception when obfuscating a dll.
Exception received:

  Exception: System.InvalidCastException: Unable to cast object of type 'dnlib.DotNet.FieldDefUser' to type 'System.String'.
    at Confuser.Renamer.BAML.BAMLStringReference.Rename(String oldName, String newName) in e:\Source\Public\Confuser2\Confuser.Renamer\BAML\BAMLStringReference.cs:line 15
  at Confuser.Renamer.Analyzers.WPFAnalyzer.PreRename(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in e:\Source\Public\Confuser2\Confuser.Renamer\Analyzers\WPFAnalyzer.cs:line 59
    at Confuser.Renamer.RenamePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Renamer\RenamePhase.cs:line 25
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 138
    at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 216
    at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 162

Protections used:

<protection id="anti dump" />
    <protection id="anti debug" />
    <protection id="anti ildasm" />
    <protection id="anti tamper">
      <argument name="key" value="dynamic" />
    </protection>
    <protection id="constants">
      <argument name="elements" value="SNPI" />
      <argument name="key" value="dynamic" />
      <argument name="decoderCount" value="7" />
    </protection>
    <protection id="ctrl flow">
      <argument name="predicate" value="expression" />
      <argument name="depth" value="5" />
    </protection>
    <protection id="resources">
      <argument name="mode" value="dynamic" />
    </protection>
    <protection id="ref proxy">
      <argument name="mode" value="strong" />
      <argument name="encoding" value="expression" />
      <argument name="internal" value="true" />
      <argument name="typeErasure" value="true" />
      <argument name="depth" value="5" />
    </protection>
    <protection id="rename" />

**Comment by yck1509** [comment]
Hi,
Please try the latest version at [the CI Server](https://ci.appveyor.com/project/yck1509/ConfuserEx).
