### ISSUE TITLE
[ERROR] Failed to resolve a type (System.Uri)

### ISSUE THREAD

**Issue by m5112638** [yck1509/ConfuserEx#306]
I am using ConfuserEx to obfuscate a PCL with renPublic set to true. However I got the following error (can't resolve type 'System.Uri'). Any help is appreciated!

[ERROR] Failed to resolve a type, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: System.Uri (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at dnlib.DotNet.TypeRef.ResolveThrow(ModuleDef sourceModule) in c:\projects\confuserex\dnlib\src\DotNet\TypeRef.cs:line 334
   at dnlib.DotNet.Extensions.ResolveTypeDefThrow(ITypeDefOrRef tdr) in c:\projects\confuserex\dnlib\src\DotNet\ICodedToken.cs:line 491
   at Confuser.Renamer.References.OverrideDirectiveReference.AddImportReference(ConfuserContext context, INameService service, ModuleDef module, MethodDef method, MemberRef methodRef) in c:\projects\confuserex\Confuser.Renamer\References\OverrideDirectiveReference.cs:line 25
   at Confuser.Renamer.References.OverrideDirectiveReference.UpdateNameReference(ConfuserContext context, INameService service) in c:\projects\confuserex\Confuser.Renamer\References\OverrideDirectiveReference.cs:line 49
   at Confuser.Renamer.RenamePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in c:\projects\confuserex\Confuser.Renamer\RenamePhase.cs:line 78
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ProtectionPipeline.cs:line 139
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 229
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 175

**Comment by yck1509** [comment]
Hi,
Please include the list of assemblies at the bottom of log, so I could see what version of system library ConfuserEx found.
