### ISSUE TITLE
ArgumentException when using ProductName and ProductVersion

### ISSUE THREAD

**Issue by caverna** [yck1509/ConfuserEx#309]
I have an application using WinForms.
At load event, usually I set the form text to `PRODUCT - vVERSION`, extracted from AssemblyInfo.cs (using the form properties `ProductName` and `ProductVersion` (inherited from 
`System.Windows.Forms.Control`)
This is causing `ArgumentException: Illegal characters in path`.
After clicking 'continue', the program behavior doesn't seems modified to me.
Commenting the line that uses these properties is enough to vanish the exception.
Below is the complete exception:
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Windows.Forms.Control.ControlVersionInfo.GetFileVersionInfo()
   at System.Windows.Forms.Control.ControlVersionInfo.get_ProductVersion()
   at System.Windows.Forms.Control.get_ProductVersion()
   at AC.MbS.App.MainForm.<.ctor>b__1_0(Object sender, EventArgs args)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by yck1509** [comment]
Hi,
Most likely the exception is caught internally, there should be no problem for it when ran outside debugger.
