### ISSUE TITLE
PDB file error while confusing Mixed Mode (Managed C++) DLL

### ISSUE THREAD

**Issue by patluze** [yck1509/ConfuserEx#321]
Hello,

I have a mixed mode (Managed C++) DLL built using VS2005  that ConfuserEx appears to successfully obfuscate.  When I choose the option to Generate Debug Symbols I receive this error:

ERROR] Unknown error occurred.
Exception: dnlib.DotNet.Pdb.Managed.PdbException: Failed to read PDB: Unexpected value
   at dnlib.DotNet.Pdb.Managed.DbiDocument.Read(IImageStream stream) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\Managed\DbiDocument.cs:line 30
   at dnlib.DotNet.Pdb.Managed.PdbReader.GetDocument(UInt32 nameId) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\Managed\PdbReader.cs:line 256
   at dnlib.DotNet.Pdb.Managed.DbiModule.ReadFiles(PdbReader reader, Dictionary`2 documents, IImageStream stream, Int64 end) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\Managed\DbiModule.cs:line 123
   at dnlib.DotNet.Pdb.Managed.DbiModule.ReadLines(PdbReader reader, IImageStream stream) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\Managed\DbiModule.cs:line 93
   at dnlib.DotNet.Pdb.Managed.DbiModule.LoadFunctions(PdbReader reader, IImageStream stream) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\Managed\DbiModule.cs:line 54
   at dnlib.DotNet.Pdb.Managed.PdbReader.ReadInternal(IImageStream stream) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\Managed\PdbReader.cs:line 114
   at dnlib.DotNet.Pdb.Managed.PdbReader.Read(IImageStream stream) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\Managed\PdbReader.cs:line 49
   at dnlib.DotNet.Pdb.Managed.SymbolReaderCreator.Create(IImageStream pdbStream) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\Managed\SymbolReaderCreator.cs:line 54
   at dnlib.DotNet.Pdb.Managed.SymbolReaderCreator.CreateFromAssemblyFile(String assemblyFileName) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\Managed\SymbolReaderCreator.cs:line 22
   at dnlib.DotNet.Pdb.SymbolReaderCreator.Create(PdbImplType pdbImpl, String assemblyFileName) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\Pdb\SymbolReaderCreator.cs:line 28
   at dnlib.DotNet.ModuleDefMD.LoadPdb(PdbImplType pdbImpl) in g:\spare\ConfuserEx-master\dnlib\src\DotNet\ModuleDefMD.cs:line 535
   at Confuser.Core.ObfAttrMarker.MarkModule(ProjectModule projModule, ModuleDefMD module, Dictionary`2 rules, Boolean isMain) in g:\spare\ConfuserEx-master\Confuser.Core\ObfAttrMarker.cs:line 297
   at Confuser.Core.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in g:\spare\ConfuserEx-master\Confuser.Core\ObfAttrMarker.cs:line 182
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in g:\spare\ConfuserEx-master\Confuser.Core\ConfuserEngine.cs:line 134
Failed at 11:25 AM, 0:00 elapsed.

I'm using a version of ConfuserEx and the yck1509 branch of dnlib that I downloaded and built today. The Generate Debug Symbols option appears to work fine for a managed assembly.  

Thanks in advance for any help in resolving this issue.

**Comment by yck1509** [comment]
Hi,
The managed PDB reader implementation assumes the input is fully managed, and may not support some C++ constructs.
