### ISSUE TITLE
Unreachable code reached

### ISSUE THREAD

**Issue by Arextion** [yck1509/ConfuserEx#329]
I keep getting an error on several of my assemblies... any ideas?

[ERROR] Unknown error occurred.
Exception: Confuser.Core.UnreachableException: Unreachable code reached.
   at Confuser.Renamer.Analyzers.LdtokenEnumAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in e:\Source\Public\Confuser2\Confuser.Renamer\Analyzers\LdtokenEnumAnalyzer.cs:line 48
   at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 103
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 56
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 139
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 208
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 162
Failed at 13:42, 0:00 elapsed.

**Comment by yck1509** [comment]
Hi,
It should normally be impossible for this error to occur. Please send me the file at confuser.net@gmail.com so that I can see what's wrong with it.

**Comment by skaliak** [comment]
FYI, I got this same error with the same stack trace, and I eventually realized that I was accidentally running confuserex on an assembly that had already been processed.  In other words, if you run confuserex on an assembly and then run it again on the output file, this error happens.  I hope this helps.
