### ISSUE TITLE
ResourceManager.GetString doesn't work after obfuscation

### ISSUE THREAD

**Issue by User199011** [yck1509/ConfuserEx#345]
Hello,

I have downloaded the last version of ConfuserEx and tried to obfuscate my project. Everything seems to work fine until I try to change the language of my application : 

                System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("fr");
                System.Threading.Thread.CurrentThread.CurrentUICulture = new CultureInfo("fr");

I have a generated resourceManager for languages and I checked its System.Globalization.CultureInfo resourceCulture variable is set to "French".

However the following line always returns the english version once confuserEx has protected my exe :
internal static string MY_TEXT{
            get {
MessageBox.Show(resourceCulture.EnglishName);
                return ResourceManager.GetString("KEY", resourceCulture);
            }
        }

I have the following configuration for my project :+1: <rule pattern="true" preset="maximum" />
and 
<rule pattern="true">
	<protection id="anti debug" />
	<protection id="anti ildasm" />
	<protection id="constants">
		<argument name="mode" value="dynamic" />
	</protection>
	<protection id="ctrl flow" />
	<protection id="rename">
		<argument name="mode" value="letters" />
	</protection>
	<protection id="ref proxy" />
	<protection id="resources" />
  </rule>

What is the problem ?

Thank you

**Comment by yck1509** [comment]
Hi,
I can't reproduce the issue here. Are you using satellite assemblies?

**Comment by User199011** [comment]
Yes I set the ResourceManager variable in a custom assembly.

**Comment by User199011** [comment]
Are you able to reproduce it ? Maybe you can give me an hint on how to avoid this behavior and still be able to user both resource Manager and ConfuserEx :)

**Comment by yck1509** [comment]
Hi,
Did you use any packers? Do you have satellite assemblies under the language folder? (e.g. If you app is in /App/App.exe, you have a dll at /App/fr/App.resources.dll)

**Comment by HACKHERS** [comment]
I confirm this. (I have files like App/fr/App.resources.dll)

**Comment by yck1509** [comment]
If you have satellite assemblies, you'll need to include them in ConfuserEx to protect it correctly.

**Comment by HACKHERS** [comment]
@yck1509 yeah it works sorry :)

**Comment by ahmedosama007** [comment]
@yck1509 When I try to add satellite assemblies to ConfuserEx I get the following error:

```
[ERROR] Failed to resolve a type, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.TypeResolveException: Could not find type: GameFire.Resources
   at dnlib.DotNet.Extensions.FindReflectionThrow(ITypeDefFinder self, String fullName) in E:\Source\Public\Confuser2\dnlib\src\DotNet\ITypeDefFinder.cs:line 105
   at Confuser.Renamer.Analyzers.ResourceAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in e:\Source\Public\Confuser2\Confuser.Renamer\Analyzers\ResourceAnalyzer.cs:line 33
   at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 133
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 55
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 138
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 219
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 173
```

**Comment by 12gods** [comment]
User199011
Have you find solution about your problem with resource files?
