### ISSUE TITLE
Compressor: Packer, causing the protection process to fail.

### ISSUE THREAD

**Issue by BinaryEvolved** [yck1509/ConfuserEx#358]
Hello,

When attempting to protect a very basic exe on maximum settings, it processes fine. If I go to the settings tab and enable the Packer:Compressor, I then get a IO error. I have attempted to run as admin but I had the same result.

Complete Error log:
```
 [INFO] ConfuserEx v0.4.0-67-g3eae208 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'BESR_Configuration Editor.exe'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
 [INFO] Processing module 'BESR_Configuration Editor.exe'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'koi'...
[DEBUG] Encrypting resources...
 [INFO] Finalizing...
 [INFO] Packing...
[DEBUG] Encrypting modules...
 [INFO] Protecting packer stub...
[DEBUG] Discovering plugins...
 [INFO] Discovered 11 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
[ERROR] An IO error occurred, check if all input/output locations are readable/writable.
Exception: System.IO.IOException: Could not open file C:\Users\BinaryEvolved\AppData\Local\Temp\g0tnfjg4.bgm\BESR_Configuration Editor.exe for reading. Error: 00000002
   at dnlib.IO.MemoryMappedFileStreamCreator.Windows.Mmap(MemoryMappedFileStreamCreator creator, Boolean mapAsImage) in c:\projects\confuserex\dnlib\src\IO\MemoryMappedFileStreamCreator.cs:line 62
   at dnlib.IO.MemoryMappedFileStreamCreator.CreateWindows(String fileName, Boolean mapAsImage) in c:\projects\confuserex\dnlib\src\IO\MemoryMappedFileStreamCreator.cs:line 165
   at dnlib.IO.ImageStreamCreator.Create(String fileName, Boolean mapAsImage) in c:\projects\confuserex\dnlib\src\IO\ImageStreamCreator.cs:line 42
   at dnlib.PE.PEImage..ctor(String fileName, Boolean mapAsImage, Boolean verify) in c:\projects\confuserex\dnlib\src\PE\PEImage.cs:line 165
   at dnlib.DotNet.MD.MetaDataCreator.Load(String fileName) in c:\projects\confuserex\dnlib\src\DotNet\MD\MetaDataCreator.cs:line 33
   at Confuser.Core.Marker.MarkProject(ConfuserProject proj, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\Marker.cs:line 100
   at Confuser.Core.PackerMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\Packer.cs:line 158
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 121
[ERROR] Failed to protect packer stub.
Failed at 4:35 AM, 0:08 elapsed.
```

Regards

**Comment by caverna** [comment]
I was having a king of error like that using some of binary releases...
When I compiled the last version, the error was gone...
Did you tried?

**Comment by yck1509** [comment]
Hi,
Please use the latest builds at the [CI Server](https://ci.appveyor.com/project/yck1509/ConfuserEx).
