### ISSUE TITLE
crash application when external assemblies are referenced 

### ISSUE THREAD

**Issue by JaspreetSinghXDA** [yck1509/ConfuserEx#368]
Ok right now i am using ConfuserEx v0.5.0-90-gc79a032 latest build

PART 1 :-
now let me explain better i can
- i created my project and include bassmod.net to include some nice chiptunes or for themeing i use metroframework or visualstyler.net
- now when i use confuserex it can protect the assembly but the external frameworks like bass.net,metro etc i have to supply them as different assemblies so that it can work and it does work when u put the external assemblies on the same folder where protected .exe is there

Now issue comes is that i want to provide it as standalone .exe file

PART 2 :- 
now i used smart assembly to embed those assemblies without any encryption just embed option and build now they are embedded in new assembly and can be run on other pc without those support assembly now i used confuser on that smart assembly .exe in which i just only embedded those files to make it standalone

now when i protect here is the error
------------------------------------
[INFO] Resolving dependencies...
[ERROR] Failed to resolve dependency of 'Keymaker.exe'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: MetroFramework, Version=1.3.5.0, Culture=neutral, PublicKeyToken=5f91a84759bf584a
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in c:\projects\confuserex\dnlib\src\DotNet\IAssemblyResolver.cs:line 113
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 267
Failed at 4:20 PM, 0:00 elapsed.
--------------------------------------
how i can i embed those assemblies and also protect with confuser ?

if i dont include any of this assembly as reference in my project it will protect the assembly properly but then i lost sound and themeing capabilities

**Comment by JaspreetSinghXDA** [comment]
cud u plz provide option to embedd assemblies ?

**Comment by JaspreetSinghXDA** [comment]
cud u plz provide option to embedd assemblies ?

**Comment by yck1509** [comment]
Hi,
You can't use ConfuserEx on already obfuscated assemblies. If you want to embed assemblies, you can use the Packer option.

**Comment by JaspreetSinghXDA** [comment]
Hi i used option packer and when it compress the file i get error cus bassmod,net is not available in that directory where packed .exe is

so means external assembly is not embedded see error below

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'BassMOD.Net, Version=2.0.0.2, Culture=neutral, PublicKeyToken=d4db1103f7215e10' or one of its dependencies. The system cannot find the file specified.
File name: 'BassMOD.Net, Version=2.0.0.2, Culture=neutral, PublicKeyToken=d4db1103f7215e10'
   at keygen.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by ivan-danilov** [comment]
@yck1509 could you elaborate why you "can't use ConfuserEx on already obfuscated assemblies"?
I have a library that is partially obfuscated (private/internal parts) and by its license I must obfuscate the rest before releasing my product. Given how it looks I'd say only renames to sequential english letters and control flow protections were applied, i.e. I can open it in ILSpy/dotPeek without issues and get a logic.
Vendor proposes using dotfuscator and even provides sample configuration, but I'd like to use ConfuserEx instead. Actually I don't have any errors during obfuscation process, but result is not executable right now (I have created some issues here). For now I believe it is related to some general issues with ConfuserEx that could be fixed, not some critical flaw.

Should I expect some significant issues due to this partial obfuscation?

**Comment by yck1509** [comment]
@ivan-danilov:  Generally, you can't use ConfuserEx on assemblies already obfuscated by ConfuserEx itself, as protections by ConfuserEx are sensitive to modification. However, if the obfuscated assemblies do not have such protections (e.g. only renaming is applied), then obfuscation could be applied without problems.
