### ISSUE TITLE
What about roslyn / vs2015 / .NET 4.6?

### ISSUE THREAD

**Issue by Mikolaytis** [yck1509/ConfuserEx#380]
it's sad that confuser can't obfuscate assemblies from vs2015. output assemblies throwing fatal errors

**Comment by Fabi** [comment]
works fine for me

**Comment by yck1509** [comment]
Hi,
Do you have any specific example that is having problem?

**Comment by rwaschhauser** [comment]
I get a MissingMethodException, but I have no idea what's the reason for the issue. 

System.MissingMethodException: Method not found: '!0[] ⁮‪​‫⁯‫‪⁫⁯‏‪⁭‭‮⁫⁯⁪‭‎‮⁬‬⁬‮‮‎⁮‍⁯‬‎‪‫‌‭⁯‎.getValues()'.

at ⁬‌⁪‎⁪‍‏‎⁭‭‎‌⁪‏⁬⁮‌‍‭⁫⁭‌⁫⁯‬⁪‏‫‎‭⁪‭⁪‎‏⁬‍⁫‫⁯‮.‎⁬‌‍‎⁮⁪⁭‪‏‎⁬⁮‪‭‌‫‪‫⁮‭⁬⁬‍⁭‌⁫‎‏‬⁭⁮‮‫⁫⁫‫⁪‮⁯‮()

at ⁬‌⁪‎⁪‍‏‎⁭‭‎‌⁪‏⁬⁮‌‍‭⁫⁭‌⁫⁯‬⁪‏‫‎‭⁪‭⁪‎‏⁬‍⁫‫⁯‮.‮‮⁪‍‪‍⁬‫⁯‬⁯‌‎‫‮⁫‬‌⁮‎⁫‏‎⁪‍‌‫⁯‏⁪‬⁬‌⁬‪​⁪‬‫⁫‮()

at beM\.J~FRE;Z4;0{OHr=@nJ3x$.‮‮⁪‍‪‍⁬‫⁯‬⁯‌‎‫‮⁫‬‌⁮‎⁫‏‎⁪‍‌‫⁯‏⁪‬⁬‌⁬‪​⁪‬‫⁫‮()

at beM\.J~FRE;Z4;0{OHr=@nJ3x$.‌‏‍⁪‫​‌‎‍‭‏‎‏⁪‮​‭‍⁭‮‬⁯⁮‫⁫‌⁫‏‭​‬‌‫‪⁪‌⁫‎⁯‬‮(​⁫‫​‌‌​⁮‮⁬‍‭‪‎⁫‍​‏‍⁫​⁬‏‫⁬‪⁯⁫⁭⁪⁭‍⁭‭‫⁫⁪⁮‫‮ )

at beM\.J~FRE;Z4;0{OHr=@nJ3x$..ctor(‌‍⁬⁫⁭⁭‪‍‮‫‫⁮​⁭‬⁮⁬‮‭‏‎‮‪‮‌‫‪⁪​⁭⁫‫⁯‬‎‎‏‬⁫‭‮ profinetDeviceCatalogService, ​⁫‫​‌‌​⁮‮⁬‍‭‪‎⁫‍​‏‍⁫​⁬‏‫⁬‪⁯⁫⁭⁪⁭‍⁭‭‫⁫⁪⁮‫‮ profinetDevice)

at ‏​⁮⁪⁯‍⁪⁯‎‪⁮‮​‪‏‌‏‪‌‏‭​​⁯⁭‎‪‎‌⁯‫‌⁯⁮‍‏⁮⁪‫‎‮.⁪⁭‮‬⁪⁫⁭⁭‪‬‫‪‎‭‬⁮‭⁮‫⁪⁭‏‏‮⁯⁮‪⁭‌⁬‮‌⁫​⁭‬‭‏⁬⁪‮(IEnumerable`1 , ⁯‌⁫‬⁭​⁪⁫⁭⁪‮‍‭‫⁯‌‏​⁮‬‎‪‍⁯‬‍⁯‫‫‭⁮​⁭⁬⁭⁬‍‏⁫‮ )

at Waschhauser.Profinet.MSBuild.Tasks.PNC.Execute()

at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()

at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by yck1509** [comment]
Hi,
Is there any sample code that can reproduce this issue?

**Comment by nlips** [comment]
It may be the bug #407

**Comment by rwaschhauser** [comment]
I'am not shure. Is there anything I can do to help you to reproduce the problem?

**Comment by altk** [comment]
Pseudocode, when I encountered the same error
```
internal interface IInterface<T> 
{
   Boolean Foo(T t);
}

abstract class AbstractClass<T> : IInterface<T>
{
    public Boolean Foo(T t) { ... }
}

sealed class Class : AbstractClass<TCLass>
{
}
}
```
```
Method not found: 'Boolean xxx.IInterface`1.Foo(!0)
```
