### ISSUE TITLE
Unknown error occurred.

### ISSUE THREAD

**Issue by itsho** [yck1509/ConfuserEx#406]
Hi.

I'm getting this error with **0.6.0** when trying anything (even Preset: **None**),
while any settings I want works on **0.5.0**

here's the error:

    Exception: System.ArgumentException: Feature property cannot be set when Exclude is true.
    at Confuser.Core.ObfAttrMarker.<ProcessAttributes>d__0.MoveNext() in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 135
    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
    at Confuser.Core.ObfAttrMarker.ProcessModule(ModuleDefMD module, Dictionary`2 rules, String snKeyPath, String snKeyPass, List`1 settingAttrs, Dictionary`2 namespaceAttrs) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 357
    at Confuser.Core.ObfAttrMarker.MarkModule(ProjectModule projModule, ModuleDefMD module, Dictionary`2 rules, Boolean isMain) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 317
    at Confuser.Core.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 230
    at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 135
    Failed at 22:57, 0:00 elapsed.

any idea?

**Comment by caverna** [comment]
Are you using in a VB.NET project just like me? (https://github.com/yck1509/ConfuserEx/issues/396)

**Comment by itsho** [comment]
No. it's a solution compiled from C# projects.

**Comment by MurariAlex** [comment]
I've stumbled on that exception in the following scenario:
```xml
		<protection id="anti debug" action="remove">
			<argument name="mode" value="antinet" />
		</protection>
```

As you can see, i've removed the protection but kept an attribute property set in the xml, the new attribute marker of ConfuserEx doesn't allow that, you have to remove all attribute properties from the excluded protections.
```xml
		<protection id="anti debug" action="remove" />
```

**Comment by yck1509** [comment]
Hi,
Do you have any usage of ObfuscationAttribute in your project?

**Comment by itsho** [comment]
Hi. No.
I don't have any usage of it in my solution.

Thanks.

**Comment by yck1509** [comment]
Hi,
Please try the latest build from [CI Server](https://ci.appveyor.com/project/yck1509/confuserex) and post the updated error message.

**Comment by itsho** [comment]
Hi.

same error with latest build (20 hours ago):


    [INFO] ConfuserEx v0.6.0 Copyright (C) Ki 2014
    [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.34209, 64 bits
    [DEBUG] Discovering plugins...
     [INFO] Discovered 10 protections, 1 packers.
    [DEBUG] Resolving component dependency...
     [INFO] Loading input modules...
     [INFO] Loading 'Z.exe'...
     [INFO] Loading 'Y.dll'...
     [INFO] Loading 'X.dll'...
    [ERROR] Unknown error occurred.
    Exception: System.ArgumentException: Feature property cannot be set when Exclude is true.
       at Confuser.Core.ObfAttrMarker.<ProcessAttributes>d__0.MoveNext() in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 135
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Confuser.Core.ObfAttrMarker.ProcessModule(ModuleDefMD module, Dictionary`2 rules, String snKeyPath, String snKeyPass, List`1 settingAttrs, Dictionary`2 namespaceAttrs) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 357
       at Confuser.Core.ObfAttrMarker.MarkModule(ProjectModule projModule, ModuleDefMD module, Dictionary`2 rules, Boolean isMain) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 317
       at Confuser.Core.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 230
       at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 135
    Failed at 10:36, 0:00 elapsed.

**Comment by caverna** [comment]
Hey! Check if there's any 'ObfuscationAttribute' that you used earlier with Eazfuscator!
The best you can do is erase all 'ObfuscationAttribute'!
Try that and update this post.

**Comment by itsho** [comment]
You are right!
I had `[System.Reflection.Obfuscation(...)]` on old class, which I forgot.

Thanks. it is working now :+1:

**Comment by cozy1** [comment]
Thanks for posting this it helped me solve a problem I was having.
