### ISSUE TITLE
Unreachable code reached / Object reference error

### ISSUE THREAD

**Issue by zaryk** [yck1509/ConfuserEx#445]
I have a console application (windows service), and an asp.net application.  Debug/Release work fine in the asp.net application using below settings, and Debug works with console application.  However, release gives 2 separate errors.  I have used the CI Build, because there was another post that mentioned so, but still continue to get the errors.  The objects are confused on post build.  The paths look correct.  If no file is specified, it builds successfully, but then there is no confused objects.  If I remove the Spartan.Core.dll, it says Unreachable code reached, and If I keep the Spartan.Core, it says Object reference error.  Then I reordered the files to be more like the asp.net, and regardless of whether spartan.core was removed or not, it says object reference error.  Debug still continues to work.  I am sending the proj and 1 library to confuser.net@gmail.com

Console Application:

```
   [ERROR] Unknown error occurred.
   Exception: Confuser.Core.UnreachableException: Unreachable code reached.
      at Confuser.Renamer.Analyzers.LdtokenEnumAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in c:\projects\confuserex\Confuser.Renamer\Analyzers\LdtokenEnumAnalyzer.cs:line 53
      at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer) in c:\projects\confuserex\Confuser.Renamer\AnalyzePhase.cs:line 117
      at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in c:\projects\confuserex\Confuser.Renamer\AnalyzePhase.cs:line 55
      at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ProtectionPipeline.cs:line 138
      at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 221
      at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 175

```

```
  [ERROR] Unknown error occurred.
  Exception: System.NullReferenceException: Object reference not set to an instance of an object.
     at Confuser.Renamer.Analyzers.LdtokenEnumAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in c:\projects\confuserex\Confuser.Renamer\Analyzers\LdtokenEnumAnalyzer.cs:line 55
     at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer) in c:\projects\confuserex\Confuser.Renamer\AnalyzePhase.cs:line 118
     at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in c:\projects\confuserex\Confuser.Renamer\AnalyzePhase.cs:line 55
     at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ProtectionPipeline.cs:line 138
     at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 219
     at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 173
  Failed at 2:19 PM, 0:01 elapsed.
```

PostBuild

```
 if not "$(ConfigurationName)" == "Debug Without Obfuscation" ( 
 "C:\Program Files\ConfuserEx\Confuser.CLI" "$(ProjectDir)\Obfuscation.crproj"
 xcopy "$(TargetDir)\Confused\*.dll" "$(TargetDir)" /Y
 )
```

Console Application CrProj:

```
<project outputDir="Confused" baseDir=".\bin\Debug" debug="true" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="normal" inherit="false">
    <protection id="anti ildasm" action="remove" />
    <protection id="anti tamper" />
    <protection id="constants" />
    <protection id="ctrl flow" />
    <protection id="anti dump" />
    <protection id="anti debug" />
    <protection id="invalid metadata" />
    <protection id="ref proxy" />
    <protection id="resources" action="remove" />
    <protection id="rename" action="remove" />
  </rule>
  <module path="ReportSchedulerExtension.dll" />
  <module path="Spartan.Core.dll" />
  <module path="Spartan.Core.Extended.dll" />
  <module path="Spartan.Event.Scheduler.Controller.dll" />
  <module path="Spartan.Event.Scheduler.exe" />
  <module path="Spartan.Inquiry.Core.dll" />
  <module path="Spartan.Inquiry.DataStore.dll" />
  <module path="Spartan.ReportManager.BLL.dll" />
  <module path="Spartan.ReportManager.Core.Crystal.dll" />
  <module path="Spartan.ReportManager.Core.dll" />
  <module path="Spartan.ReportManager.DAL.dll" />
  <module path="Spartan.ReportManager.Entity.dll" />
  <module path="Zarysoft.dll" />
</project>
```

Asp.net crProj:

```
<project outputDir="Confused" baseDir=".\bin" debug="true" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="normal" inherit="false">
    <protection id="anti ildasm" action="remove" />
    <protection id="anti tamper" />
    <protection id="constants" />
    <protection id="ctrl flow" />
    <protection id="anti dump" />
    <protection id="anti debug" />
    <protection id="invalid metadata" />
    <protection id="ref proxy" />
    <protection id="resources" action="remove" />
    <protection id="rename" action="remove" />
  </rule>
  <module path="Zarysoft.dll" />
  <module path="Spartan.Core.dll" />
  <module path="Spartan.Core.Extended.dll" />
  <module path="Spartan.Inquiry.Core.dll" />
  <module path="Spartan.Inquiry.DataStore.dll" />
  <module path="Spartan.ReportManager.BLL.dll" />
  <module path="Spartan.ReportManager.Core.Crystal.dll" />
  <module path="Spartan.ReportManager.Core.dll" />
  <module path="Spartan.ReportManager.Core.Xtra.dll" />
  <module path="Spartan.ReportManager.DAL.dll" />
  <module path="Spartan.ReportManager.Entity.dll" />
  <module path="Spartan.ReportManager.UI.Web.dll" />
</project>
```

Console after reorder:

```
<project outputDir="Confused" baseDir=".\bin\Debug" debug="true" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="normal" inherit="false">
    <protection id="anti ildasm" action="remove" />
    <protection id="anti tamper" />
    <protection id="constants" />
    <protection id="ctrl flow" />
    <protection id="anti dump" />
    <protection id="anti debug" />
    <protection id="invalid metadata" />
    <protection id="ref proxy" />
    <protection id="resources" action="remove" />
    <protection id="rename" action="remove" />
  </rule>

  <module path="Zarysoft.dll" />
  <module path="Spartan.Core.dll" />
  <module path="Spartan.Core.Extended.dll" />
  <module path="Spartan.Inquiry.Core.dll" />
  <module path="Spartan.Inquiry.DataStore.dll" />
  <module path="Spartan.ReportManager.BLL.dll" />
  <module path="Spartan.ReportManager.Core.Crystal.dll" />
  <module path="Spartan.ReportManager.Core.dll" />
  <module path="Spartan.ReportManager.DAL.dll" />
  <module path="Spartan.ReportManager.Entity.dll" />
  <module path="ReportSchedulerExtension.dll" />
  <module path="Spartan.Event.Scheduler.Controller.dll" />
  <module path="Spartan.Event.Scheduler.exe" />

</project>
```

**Comment by zaryk** [comment]
I can also set everything to be removed, and get object reference error.

```
<project outputDir="Confused" baseDir=".\bin\Debug" debug="false" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="normal" inherit="false">
    <protection id="anti ildasm" action="remove" />
    <protection id="anti tamper"  action="remove"/>
    <protection id="constants" action="remove" />
    <protection id="ctrl flow" action="remove" />
    <protection id="anti dump" action="remove"  />
    <protection id="anti debug"  action="remove"/>
    <protection id="invalid metadata" action="remove"/>
    <protection id="ref proxy"  action="remove"  />
    <protection id="resources" action="remove" />
    <protection id="rename" action="remove" />
  </rule>

  <module path="Zarysoft.dll" />
</project>
```

**Comment by yck1509** [comment]
Hi,
I tried the dll and settings you sent to me and it does not have any error in the protection process. Did you try the latest build from the [CI Server](https://ci.appveyor.com/project/yck1509/ConfuserEx)?

**Comment by zaryk** [comment]
Yes, I did.  I figure you might not get the error and that it could be something environmental.  I will see if I can do something and do some testing on other machines.

**Comment by zaryk** [comment]
i grabbed the latest since it looked like there are a couple changes since I posted.  I get this now.  That particularly dll shouldn't have any dependencies except for system dependencies.  Strange that it still builds fine when in debug.  The confuserex ui seems to give the error regardless.  I will be doing more testing on it later today.

[ERROR] Failed to resolve dependency of 'Zarysoft.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: vSxypAORWxKIgFwXqCMPBUIZsbCK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in c:\projects\confuserex\dnlib\src\DotNet\IAssemblyResolver.cs:line 113
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 267
Failed at 10:33 AM, 0:01 elapsed.

**Comment by zaryk** [comment]
duh....i just answered my own question.  The crproj has .\bin\Debug as the basedir, so I for now I will have to create two configs and make sure the correct one is used.  When changing to release, it works fine.
