### ISSUE TITLE
Exception: System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by SieRaybould** [yck1509/ConfuserEx#515]
ConfuserEx is crashing when I try to rename the symbols in my xamarin DLL.

 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[ERROR] Unknown error occurred.
Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Confuser.Renamer.VTable.ConstructVTable(TypeDef typeDef, VTableStorage storage) in c:\projects\confuserex\Confuser.Renamer\VTable.cs:line 223
   at Confuser.Renamer.VTableStorage.GetOrConstruct(TypeDef type) in c:\projects\confuserex\Confuser.Renamer\VTable.cs:line 332
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in c:\projects\confuserex\Confuser.Renamer\AnalyzePhase.cs:line 46
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ProtectionPipeline.cs:line 139
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 221
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 175
Failed at 13:43, 0:01 elapsed.

This is using ConfuserEx v1.0.0-2-g44eb522

Regards,
Simon

**Comment by matas2007** [comment]
Hi,

I had similar error. After hours of debugging I noticed that ConfuserEx doesn't like desctructors. Try to comment-out all destructors in your code and see if it helps.

Matas

**Comment by edwinov** [comment]
I had the same problem. After debugging I discovered that (in my case) the problem is in VTable.cs in the line containing 

`var targetSlot = vTbl.AllSlots.Single(slot => slot.MethodDef == targetMethod);`

the == comparison does not return true for a Finalize method which makes the .Single throw an exception. I changed the code to the following to fix the problem:

// line changed
var targetSlot = GetSingleSlot(vTbl.AllSlots, targetMethod);

// function added
static VTableSlot GetSingleSlot(List<VTableSlot> list, MethodDef method)
 {
	        int found = 0;
	        VTableSlot result = null;
	        for (int i = 0; i < list.Count; i++)
	        {
	            var slot = list[i];
	            if (slot.MethodDef == method)
	            {
	                result = slot;
	                found++;
	            }
	        }

	        if (found == 0)
	        {
                for (int i = 0; i < list.Count; i++)
                {
                    var slot = list[i];
                    if (slot.MethodDef.ToString() == method.ToString())
                    {
                        result = slot;
                        found++;
                    }
                }
            }

	        if (found == 1)
	            return result;

	        throw new InvalidOperationException();
	    }

That's it. The function does the same as .Single except if at first is hasn't found the method it looks again but now based on a string comparison. 

Edwin

PS This is my very first post here on github and I don't quite get the inserting of code yet.
