### ISSUE TITLE
Unable to confuse UWP class library.

### ISSUE THREAD

**Issue by zipswich** [yck1509/ConfuserEx#523]
The following error is generated when confusing a UWP class library:
```
[ERROR] Failed to resolve dependency of 'MyClassLibraryUWP.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Windows.Foundation.UniversalApiContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in E:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:line 113
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 264
```

**Comment by nexussays** [comment]
Have you had any luck @zipswich? I'm encountering the same error with a different library. I'm presuming that ConfuserEx is looking for packages.config instead of project.json

**Comment by zipswich** [comment]
No unfortunately.

**Comment by baskren** [comment]
It's been a year.  Any progress?
