### ISSUE TITLE
Unable to confuse netmodules

### ISSUE THREAD

**Issue by cia48621793** [yck1509/ConfuserEx#557]
```c#
 [INFO] ConfuserEx v1.0.0 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'Payload.netmodule'...
[ERROR] Unknown error occurred.
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Confuser.Core.ObfAttrMarker.ReadObfuscationAttributes(IHasCustomAttribute item) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 136
   at Confuser.Core.ObfAttrMarker.MarkModule(ProjectModule projModule, ModuleDefMD module, Dictionary`2 rules, Boolean isMain) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 373
   at Confuser.Core.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 292
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 134
Failed at 9:58 AM, 0:00 elapsed.
```

**Comment by XenocodeRCE** [comment]
Check if .net module is not already obfuscated
