### ISSUE TITLE
Could not convert RVA to file offset for VS2015 C++ x86

### ISSUE THREAD

**Issue by gpetrou** [yck1509/ConfuserEx#567]
I created a VS2015 Update 3 C++ Managed dll.
When I obfuscate the x64 release mode it seems to be working OK.
When I obfuscate the x86 release mode I get the following:

> [ERROR] Unknown error occurred.
Exception: dnlib.DotNet.Writer.ModuleWriterException: Could not convert RVA to file offset
   at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args) in E:\Source\Public\Confuser2\dnlib\src\DotNet\ILogger.cs:line 456
   at dnlib.DotNet.Writer.NativeModuleWriter.UpdateVTableFixups(BinaryWriter writer) in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\NativeModuleWriter.cs:line 669
   at dnlib.DotNet.Writer.NativeModuleWriter.UpdateHeaderFields(BinaryWriter writer) in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\NativeModuleWriter.cs:line 548
   at dnlib.DotNet.Writer.NativeModuleWriter.WriteFile() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\NativeModuleWriter.cs:line 371
   at dnlib.DotNet.Writer.NativeModuleWriter.WriteImpl() in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\NativeModuleWriter.cs:line 197
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest) in E:\Source\Public\Confuser2\dnlib\src\DotNet\Writer\ModuleWriterBase.cs:line 503
   at Confuser.Core.ConfuserEngine.WriteModule(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 404
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 135
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 244
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 175

If I compile the same project with VS2012 it seems to work.
Has anyone else faced this issue? Any ideas how to address it?

**Comment by gpetrou** [comment]
Apparently, if I use v140_xp instead of v140 in VS2015 it seems to work.

**Comment by GoKarliGo** [comment]
Setting the "Platform Toolset" to v140_xp results in compilation errors of my project because System.IO.Compression and other namespaces cannot be found.
I don't think that "stepping back" is the right solution anyway.

Some ideas to make it work with v140 ?
