### ISSUE TITLE
Packer -> An item with the same key has already been added - DevExpress

### ISSUE THREAD

**Issue by rolandh** [yck1509/ConfuserEx#568]
Simply trying to pack an exe with DevExpress 16.1 assemblies. You can reproduce it using their sample applications and only choosing to use the packer with no protections enabled.

If I pack my exe with my own DLLs but not with devexpress it succeeds but the application fails to start on invocationtarget in mscorlib which I cannot debug to find out what has gone wrong. I suspect it can't find a reference.

Can I choose to only pack some files into the EXE with others remaining external? How can I use your software with an application that uses devexpress?

[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[ERROR] Unknown error occurred.
Exception: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Confuser.Renamer.VTable.Inherits(VTableConstruction vTbl, VTable baseVTbl) in e:\Source\Public\Confuser2\Confuser.Renamer\VTable.cs:line 296
   at Confuser.Renamer.VTable.ConstructVTable(TypeDef typeDef, VTableStorage storage) in e:\Source\Public\Confuser2\Confuser.Renamer\VTable.cs:line 155
   at Confuser.Renamer.VTableStorage.GetOrConstruct(TypeDef type) in e:\Source\Public\Confuser2\Confuser.Renamer\VTable.cs:line 332
   at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 46
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 139
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 221
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 175
Failed at 8:25 AM, 0:18 elapsed.

**Comment by rolandh** [comment]
Anyone?

**Comment by bazuka5801** [comment]
Same problem

**Comment by rolandh** [comment]
Just don't include them.

**Comment by controlbreak** [comment]
any update on this? i too have the same problem

**Comment by lorington** [comment]
@controlbreak please contact me via e-mail: lorington@mail.ru
I think we have common interest.
