### ISSUE TITLE
Issue with android

### ISSUE THREAD

**Issue by ShwetaVHS** [yck1509/ConfuserEx#585]
While protecting my android project dll using confuserEX, it is throwing exception, below is complete stacktrace. 

 [INFO] ConfuserEx v0.6.0 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
[ERROR] An IO error occurred, check if all input/output locations are readable/writable.
Exception: System.IO.IOException: Could not open file projectPath.dll for reading. Error: 00000002
   at dnlib.IO.MemoryMappedFileStreamCreator.Windows.Mmap(MemoryMappedFileStreamCreator creator, Boolean mapAsImage) in E:\Source\Public\Confuser2\dnlib\src\IO\MemoryMappedFileStreamCreator.cs:line 66
   at dnlib.IO.MemoryMappedFileStreamCreator.CreateWindows(String fileName, Boolean mapAsImage) in E:\Source\Public\Confuser2\dnlib\src\IO\MemoryMappedFileStreamCreator.cs:line 188
   at dnlib.IO.ImageStreamCreator.Create(String fileName, Boolean mapAsImage) in E:\Source\Public\Confuser2\dnlib\src\IO\ImageStreamCreator.cs:line 42
   at dnlib.PE.PEImage..ctor(String fileName, Boolean mapAsImage, Boolean verify) in E:\Source\Public\Confuser2\dnlib\src\PE\PEImage.cs:line 164
   at dnlib.DotNet.MD.MetaDataCreator.Load(String fileName) in E:\Source\Public\Confuser2\dnlib\src\DotNet\MD\MetaDataCreator.cs:line 32
   at Confuser.Core.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 199
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 134
Failed at 4:29 PM, 0:00 elapsed.

Kindly Suggest.

**Comment by ElenaMilito** [comment]
Confuser don't support android application.

**Comment by MichaelRumpler** [comment]
Of course it does!

See https://forums.xamarin.com/discussion/comment/241880#Comment_241880 for detailed instructions how to get it running.

Your error message is pretty self explaining.
System.IO.IOException: Could not open file projectPath.dll for reading

Your dll cannot be found. Check the path+name.

**Comment by ShwetaVHS** [comment]
When I removed rules from .crproj, it is working fine, so I think there is not any issue on loading of project path.
