### ISSUE TITLE
Commit ccfa393 yields Error

### ISSUE THREAD

**Issue by codingdave** [yck1509/ConfuserEx#593]
Please revert the commit ccfa393 as it constitutes a regression for my WPF+Winforms project.

The issue I get on the command line is:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Confuser.Core.ConfuserEngine.PrintEnvironmentInfo(ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Confuser.CLI.Program.RunProject(ConfuserParameters parameters)
   at Confuser.CLI.Program.Main(String[] args)
```

The real issue is:

`System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Confuser.Core
  StackTrace:
       at Confuser.Core.ConfuserEngine.PrintEnvironmentInfo(ConfuserContext context) in D:\Projects\ConfuserEx.git\Confuser.Core\ConfuserEngine.cs:line 527
       at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in D:\Projects\ConfuserEx.git\Confuser.Core\ConfuserEngine.cs:line 180
       at Confuser.Core.ConfuserEngine.<>c__DisplayClass3.<Run>b__2() in D:\Projects\ConfuserEx.git\Confuser.Core\ConfuserEngine.cs:line 68
       at System.Threading.Tasks.Task.Execute()
  InnerException: 
`

**Comment by codingdave** [comment]
Sorry, this issue is not present here as the commit is part of CubeCoders/ConfuserEx-Reborn
