### ISSUE TITLE
Issue when trying to protect file.

### ISSUE THREAD

**Issue by trollmad3** [yck1509/ConfuserEx#605]
This says everytime i try to protect one of my files.

[ERROR] Unknown error occurred.
Exception: System.BadImageFormatException: .NET data directory RVA is 0
   at dnlib.DotNet.MD.MetaDataCreator.Create(IPEImage peImage, Boolean verify) in E:\Source\Public\Confuser2\dnlib\src\DotNet\MD\MetaDataCreator.cs:line 176
   at dnlib.DotNet.MD.MetaDataCreator.Load(String fileName) in E:\Source\Public\Confuser2\dnlib\src\DotNet\MD\MetaDataCreator.cs:line 32
   at Confuser.Core.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ObfAttrMarker.cs:line 292
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 134
Failed at 7:44 AM, 0:00 elapsed.

**Comment by trollmad3** [comment]
@NhocKun This will probably never get fixed as the last fix was `Jul 1, 2016`.

**Comment by ichei83** [comment]
Hi,

i took your latest version and tried to confuse c++ exe file and got same exception as above.
Can you please advise.

Thanks,
Yishai
