### ISSUE TITLE
Error - Failed to resolve a type - Any help is appreciated

### ISSUE THREAD

**Issue by jxreilly** [yck1509/ConfuserEx#657]
07:19:32 [ERROR] Failed to resolve a type, check if all dependencies are present in the correct version.
07:19:33 Exception: dnlib.DotNet.TypeResolveException: Could not resolve type: nsoftware.IPWorks.Smtp/OnSSLServerAuthenticationHandler (nsoftware.IPWorks, Version=16.0.6588.0, Culture=neutral, PublicKeyToken=cdc168f89cffe9cf)
07:19:33    at dnlib.DotNet.TypeRef.ResolveThrow(ModuleDef sourceModule) in E:\Source\Public\Confuser2\dnlib\src\DotNet\TypeRef.cs:line 334
07:19:33    at dnlib.DotNet.Extensions.ResolveTypeDefThrow(ITypeDefOrRef tdr) in E:\Source\Public\Confuser2\dnlib\src\DotNet\ICodedToken.cs:line 491
07:19:33    at Confuser.Renamer.Analyzers.InterReferenceAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in e:\Source\Public\Confuser2\Confuser.Renamer\Analyzers\InterReferenceAnalyzer.cs:line 22
07:19:33    at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 103
07:19:33    at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 56
07:19:33    at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 139
07:19:33    at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 208
07:19:33    at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 162
07:19:33 [ERROR] ---BEGIN DEBUG INFO---
07:19:33 [ERROR] Installed Framework Versions:
07:19:33 [ERROR]     v2.0.50727  2.0.50727.4927
07:19:33 [ERROR]     v3.0  3.0.30729.4926
07:19:33 [ERROR]     v3.5  3.5.30729.4926
07:19:33 [ERROR]     v4
07:19:33 [ERROR]     Client  4.7.02053
07:19:33 [ERROR]     Full  4.7.02053
07:19:33 [ERROR]     v4.0
07:19:33 [ERROR]     Client  4.0.0.0
07:19:33 [ERROR]     v4.5 460805
07:19:33 [ERROR] 
07:19:33 [ERROR] Cached assemblies:
07:19:33 [ERROR]     Subsystems.Common, Version=10.0.0.3670, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\Subsystems.Common.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         MetasysCore, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         Constants, Version=3.0.0.2804, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         Metasys.Messaging, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         MetasysWebServices, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         Jci.Metasys.MessageBus.UserAdmin, Version=38.0.0.0, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         ICSharpCode.SharpZipLib, Version=0.85.2.329, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
07:19:33 [ERROR]         BACnetEncoding, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         nunit.framework, Version=2.4.1.0, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77
07:19:33 [ERROR]         System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         msl, Version=2.1.0.373, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         nsoftware.IPWorks, Version=16.0.6588.0, Culture=neutral, PublicKeyToken=cdc168f89cffe9cf
07:19:33 [ERROR]         log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
07:19:33 [ERROR]         System.Runtime.Serialization.Formatters.Soap, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         Subsystems.Radius, Version=10.0.0.3670, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]     WebServices.Common, Version=10.0.0.3670, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\WebServices.Common.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         Subsystems.Common, Version=10.0.0.3670, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         MetasysWebServices, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         MetasysCore, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         Constants, Version=3.0.0.2804, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         Subsystems.Radius, Version=10.0.0.3670, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         Metasys.Messaging, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll)
07:19:33 [ERROR]     System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Data.SqlXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     MetasysCore, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\MetasysCore.dll)
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Web.Services, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         BACnetEncoding, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         Constants, Version=3.0.0.2779, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     Constants, Version=3.0.0.2804, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\Constants.dll)
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     Metasys.Messaging, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\Metasys.Messaging.dll)
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         BACnetEncoding, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         Constants, Version=3.0.0.2779, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         MetasysCore, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     MetasysWebServices, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\MetasysWebServices.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         MetasysCore, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         BACnetEncoding, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         msl, Version=2.1.0.373, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         Constants, Version=3.0.0.2779, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         ICSharpCode.SharpZipLib, Version=0.85.2.329, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
07:19:33 [ERROR]         System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     Jci.Metasys.MessageBus.UserAdmin, Version=38.0.0.0, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\Jci.Metasys.MessageBus.UserAdmin.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.ServiceProcess\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.ServiceProcess.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Configuration.Install, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     ICSharpCode.SharpZipLib, Version=0.85.2.329, Culture=neutral, PublicKeyToken=1b03e6acf1164f73 (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\ICSharpCode.SharpZipLib.dll)
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     BACnetEncoding, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\BACnetEncoding.dll)
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.NET\assembly\GAC_32\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Web.RegularExpressions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Web.ApplicationServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
07:19:33 [ERROR]         System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
07:19:33 [ERROR]         System.DirectoryServices.Protocols, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Runtime.Caching, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     System.Web.Services, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     nunit.framework, Version=2.4.1.0, Culture=neutral, PublicKeyToken=96d09a1eb7f44a77 (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\nunit.framework.dll)
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     System.DirectoryServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.DirectoryServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.DirectoryServices.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Management\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Management.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Configuration.Install, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         Microsoft.JScript, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     msl, Version=2.1.0.373, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\msl.dll)
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Security, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     nsoftware.IPWorks, Version=8.1.4315.0, Culture=neutral, PublicKeyToken=cdc168f89cffe9cf (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\nsoftware.IPWorks.dll)
07:19:33 [ERROR]         System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         nsoftware.System, Version=10.0.0.0, Culture=neutral, PublicKeyToken=cdc168f89cffe9cf
07:19:33 [ERROR]         System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     nsoftware.IPWorks, Version=8.1.4315.0, Culture=neutral, PublicKeyToken=cdc168f89cffe9cf (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\nsoftware.IPWorks.dll)
07:19:33 [ERROR]         System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         nsoftware.System, Version=10.0.0.0, Culture=neutral, PublicKeyToken=cdc168f89cffe9cf
07:19:33 [ERROR]         System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\log4net.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]         System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     System.Runtime.Serialization.Formatters.Soap, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime.Serialization.Formatters.Soap\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Serialization.Formatters.Soap.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]     System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
07:19:33 [ERROR]     Subsystems.Radius, Version=10.0.0.3670, Culture=neutral, PublicKeyToken=null (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\Subsystems.Radius.dll)
07:19:33 [ERROR]         mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
07:19:33 [ERROR]         msl, Version=2.1.0.373, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]         MetasysWebServices, Version=8.0.0.814, Culture=neutral, PublicKeyToken=null
07:19:33 [ERROR]     mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\assembly\GAC_32\mscorlib\2.0.0.0__b77a5c561934e089\mscorlib.dll)
07:19:33 [ERROR] ---END DEBUG INFO---

**Comment by XenocodeRCE** [comment]
Could not resolve type: nsoftware.IPWorks.Smtp/OnSSLServerAuthenticationHandler (nsoftware.IPWorks, Version=16.0.6588.0, Culture=neutral, PublicKeyToken=cdc168f89cffe9cf)

loaded types : 
[...]
nsoftware.IPWorks, Version=16.0.6588.0, Culture=neutral, PublicKeyToken=cdc168f89cffe9cf
[...]
nsoftware.IPWorks, Version=8.1.4315.0, Culture=neutral, PublicKeyToken=cdc168f89cffe9cf (E:\workspace\g3_managed-pr\g3_master_solution\Managed\bin\Release.Server\nsoftware.IPWorks.dll)


Allegedly you have referenced v16 but in folder there is only v8.1. Just swap the files

**Comment by waelshamiri** [comment]
Help me plzzzzzzzzz!

[ERROR] Failed to resolve dependency of 'WpfApp1.exe'.
1> Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Microsoft.AspNetCore.SignalR.Client.Core, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
1> عند dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) في E:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:السطر 113
1> عند Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) في e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:السطر 264
1> Failed at 06:30 م, 0:00 elapsed.

I need a help and I thank everyone who can help me
