### ISSUE TITLE
Enhancement of the Project

### ISSUE THREAD

**Issue by debpedrano** [yck1509/ConfuserEx#667]
Greetings PO

I would like to submit a logo design for your project, is there any chance I can contribute ?

**Comment by shytikov** [comment]
I believe you can just create pull request for that. And when next release will be ready it (probably) will be included. I have seen icons in the **ConfuserEx/additional** folder.

**Comment by shytikov** [comment]
Just learned that project is abandoned. I have forked and so far interested to merge all pull requests to it (I need it for my other projects). If you would like to participate we can combine our efforts.

**Comment by debpedrano** [comment]
@shytikov  I would love to work with you :) two idea is better than one, so it is not a problem

**Comment by shytikov** [comment]
My plan is to merge all pull-request that are pending, compile the code with most recent dependencies and put it to NuGet. 

If everything will went well with that, I would be logical to use renewed logo that you will provide.

**Comment by debpedrano** [comment]
I believe in you, i know you can do those works. Just enjoy working @shytikov , i will work on the logo and banner part.

**Comment by mkaring** [comment]
@shytikov I already started basically what you want to do as well. Checkout my fork. I also merged some of the pull requests already and fixed a few things of my own.

**Comment by debpedrano** [comment]
great, @shytikov someone is helping you to make the project better. awesome work @mkaring  !

**Comment by shytikov** [comment]
Superb! I can abandon my fork then and continue work on yours instead!

**Comment by MurariAlex** [comment]
@mkaring That´s great. I will keep looking into your fork too.

**Comment by debpedrano** [comment]
@shytikov if you have any desired design for the project, feel free to tell me. I have lots of designs on my mind, but your perspective for the design is important. 

![image](https://user-images.githubusercontent.com/40510200/42624529-268524cc-85f8-11e8-93a5-2f6eccf47dc1.png)

**Comment by bprg** [comment]
@mkaring I tried Compressor fail to compress file.

[ERROR] Unknown error occurred.
Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Confuser.Protections.Compress.ExtractPhase.ResourceRecorder.WriterEvent(Object sender, ModuleWriterEventArgs e)
   at dnlib.DotNet.Writer.EventHandler2`1.Invoke(Object sender, TEventArgs e)
   at dnlib.DotNet.Writer.ModuleWriterOptionsBase.RaiseEvent(Object sender, ModuleWriterEventArgs e)
   at dnlib.DotNet.Writer.ModuleWriterBase.OnWriterEvent(ModuleWriterEvent evt)
   at dnlib.DotNet.Writer.ModuleWriterBase.Metadata_MetadataEvent(Object sender, MetadataWriterEventArgs e)
   at dnlib.DotNet.Writer.Metadata.OnMetadataEvent(MetadataEvent evt)
   at dnlib.DotNet.Writer.Metadata.Create()
   at dnlib.DotNet.Writer.Metadata.CreateTables()
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.ModuleDef.Write(Stream dest, ModuleWriterOptions options)
   at Confuser.Core.ConfuserEngine.WriteModule(ConfuserContext context)
   at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context)
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token)

**Comment by XenocodeRCE** [comment]
@bprg does it work with ConfuserEX 1.0.0 ? 

I'm revamping the project step after step here : https://github.com/XenocodeRCE/neo-ConfuserEx

**Comment by bprg** [comment]
> does it work with ConfuserEX 1.0.0 ?
Yes works properly, @mkaring ported to new version dnlib that's why it does not work properly.

**Comment by XenocodeRCE** [comment]
@bprg Ok, I see, thanks for letting me know 👍 

There is 0 valid argument as far as obfuscation is concerned to move to the newer version of dnlib however.

**Comment by mkaring** [comment]
The reason I ported to the new version is that the new version of dnlib supports the portable format of the pdb files. The current version does not.

**Comment by mkaring** [comment]
@bprg I found the possible reason for the problem. Is there any chance you can share the assembly you tried to compress with me? There are multiple reasons why this could go wrong. I want to ensure that I do not miss anything.

**Comment by mkaring** [comment]
@bprg I fixed the problem based on my tests. Would be great if you could test it again yourself. If the issue is not resolved, it would be nice if you could add the issue to my fork, as the version in this repository is not affected by the issue and I don't want to clutter this issue. :wink:

**Comment by MurariAlex** [comment]
@mkaring The issue tab of your repository is not enabled.

**Comment by mkaring** [comment]
@MurariAlex Fixed that.

**Comment by bprg** [comment]
@mkaring Thank you, Now works properly.

**Comment by 0xd4d** [comment]
Two forks already by @XenocodeRCE and @mkaring , great but I think it would be better if they were merged. It's more likely that it will survive.

**Comment by XenocodeRCE** [comment]
@0xd4d @mkaring fork uses latest dnlib version which I can't bear (sorry). I'll stick with the classic and continue on my side following latest Ki's recommendations.

**Comment by MurariAlex** [comment]
@0xd4d @XenocodeRCE @mkaring Apart from the portable pdb compatibility, there is any other benefit in using the latest version of dnlib? Maybe bug fixes or a more stable assembly writing process or framework compatibility? If there´s not, maybe @mkaring can push his stuuf into @XenocodeRCE fork without the latest dnlib stuff, I saw that he made some improvements in the analyzers that can be useful.

**Comment by 0xd4d** [comment]
@MurariAlex Have a look in the git history, the dnlib used by ConfuserEx is at least two years old.

It's more important to try to use just one fork since more forks = more likely each fork will die.

**Comment by XenocodeRCE** [comment]
@0xd4d I prefer epistemic diversity 🍷

**Comment by XenocodeRCE** [comment]
@mkaring current branches works flowlessly for me ?

**Comment by debpedrano** [comment]
hello @everyone , is there any possible my logo will be merge on this project ?

**Comment by XenocodeRCE** [comment]
@debpedrano if you give authorisation I can use it. But it is not possible on *this* repo because owner leaved.

**Comment by mkaring** [comment]
@debpedrano I'll gladly use it once I rework the UI. Do you happen to have those logos as SVG images? Would be great to ensure that the UI scales properly on high-res monitors.

**Comment by debpedrano** [comment]
@XenocodeRCE  @mkaring  sure, you can freely use my logo . just tell me what sizes you need, or maybe the svg file.
