### ISSUE TITLE
ConfuserEx does not support by default Fips

### ISSUE THREAD

**Issue by adamsh25** [yck1509/ConfuserEx#670]
Is it possible to configure to support FIPS? or should I change the algo tho be other than SHA256 manually?

[ERROR] Error occured during initialization of 'Confuser Core'.
Exception: System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.SHA256Managed..ctor()
   at Confuser.Core.Services.RandomGenerator.Seed(String seed) in e:\Source\Public\Confuser2\Confuser.Core\Services\RandomService.cs:line 41
   at Confuser.Core.CoreComponent.Initialize(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\CoreComponent.cs:line 75
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 151
Failed at 2:23 PM, 0:00 elapsed.

**Comment by XenocodeRCE** [comment]
Hello @adamsh25 

please provide a file so we can fix the repo to handle FIPS

**Comment by XenocodeRCE** [comment]
btw https://stackoverflow.com/questions/14509354/this-implementation-is-not-part-of-the-windows-platform-fips-validated-cryptogra

**Comment by adamsh25** [comment]
Thank you for the quick response, We need to support FIPS, the stackoverflow thread is not relevant for us, but I managed to change the code, the core and the rename service projects to support hmacsha256  only instead of SHA1 and SHA256, FIPS is strict and does bot accept standard SHA256 and SHA1. recompiled and now it works.
